name: Jira Smoke E2E Cucumber

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Install dependencies
        run: mvn install -DskipTests -Dskip.cucumber.reports=true

      - name: Create jira.properties file
        run: |
          echo "auth=Basic ${{ secrets.JIRA_AUTH }}" > src/main/resources/jira.properties
          echo "baseUrl=${{ secrets.JIRA_BASE_URL }}" >> src/main/resources/jira.properties
          echo "projectKey=${{ secrets.JIRA_PROJECT_KEY }}" >> src/main/resources/jira.properties
          echo "issueType=${{ secrets.JIRA_ISSUE_TYPE }}" >> src/main/resources/jira.properties

      - name: Run tests
        run: mvn test -Dtest=JiraSmokeE2ECucumberTest verify

      - name: Collect artifacts
        uses: actions/upload-artifact@v2
        with:
          name: cucumber-html-reports
          path: target/cucumber-html-reports